image: nixos/nix:2.2.1

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_AUTH_CONFIG: '{ "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_AUTH" } }}'
  TARGET_HOST: staging.datahub.bbnavi.de

services:
  - docker:dind

stages:
  - build
  - tag

build:
  stage: build
  before_script:
    - nix-env -iA nixpkgs.docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker pull $CI_REGISTRY_IMAGE:tileserver || true
    - docker build -f Dockerfile.martin --cache-from $CI_REGISTRY_IMAGE:tileserver  --tag $CI_REGISTRY_IMAGE:tileserver .
    - docker push $CI_REGISTRY_IMAGE:tileserver

  only:
    - master

tag:
  stage: tag
  before_script:
    - nix-env -iA nixpkgs.docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:production
    - docker push $CI_REGISTRY_IMAGE:production
  only:
    - master
