version: '3.7'

services:
  tile_server:
    build:
      context: .
      dockerfile: Dockerfile.martin
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.port=5000
      - traefik.frontend.rule=Host:tile-server.smart-village.docker.localhost
  app:
    build:
      context: .
    environment:
      RAILS_ENV: development
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/unicorn.rb:/app/config/unicorn.rb

  nginx:
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.frontend.rule=Host:server.smart-village.docker.localhost

  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432
