version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    command: bin/delayed_job start
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: smart-village-app-mainserver-database-yml
        target: /app/config/database.yml
      - source: smart-village-app-mainserver-unicorn-rb
        target: /app/config/unicorn.rb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  cron_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    command: bin/start-cron.sh
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: smart-village-app-mainserver-database-yml
        target: /app/config/database.yml
      - source: smart-village-app-mainserver-unicorn-rb
        target: /app/config/unicorn.rb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: smart-village-app-mainserver-database-yml
        target: /app/config/database.yml
      - source: smart-village-app-mainserver-unicorn-rb
        target: /app/config/unicorn.rb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    networks: [default, public]
    configs:
      - source: smart-village-app-mainserver-nginx-conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.frontend.rule=Host:smartvillage.app
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7.21
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: smart
      MYSQL_DATABASE: smart
      MYSQL_USER: smart
      MYSQL_PASSWORD: smart
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db:
  unicorn:
  assets:

configs:
  smart-village-app-mainserver-nginx-conf:
    external: true
  smart-village-app-mainserver-database-yml:
    external: true
  smart-village-app-mainserver-unicorn-rb:
    external: true

networks:
  public:
    external: true
  bbnavi-redis-server:
    external: true
