configs:
  bbnavi-datahub-credentials:
    external: true
    name: bbnavi-datahub-credentials
  mainserver-common-master-key:
    external: true
    name: mainserver-common-master-key
  smart-village-app-mainserver-nginx-conf:
    external: true
    name: smart-village-app-mainserver-nginx-conf
networks:
  adminer:
    external: true
    name: adminer
  bbnavi-redis-server:
    external: true
    name: bbnavi-redis-server
  public:
    external: true
    name: public
services:
  app:
    configs:
    - source: bbnavi-datahub-credentials
      target: /app/releases/bbnavi/credentials.yml
    - source: mainserver-common-master-key
      target: /app/config/master.key
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      SVA_COMMUNITY: bbnavi
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      bbnavi-redis-server: {}
      default: {}
    volumes:
    - assets:/assets:rw
    - unicorn:/unicorn:rw
  cron_job:
    command: bin/start-cron.sh
    configs:
    - source: bbnavi-datahub-credentials
      target: /app/releases/bbnavi/credentials.yml
    - source: mainserver-common-master-key
      target: /app/config/master.key
    deploy:
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.schedule: 1 1 1 * * *
        swarm.cronjob.skip-running: "true"
        traefik.docker.network: public
      replicas: 0
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      SVA_COMMUNITY: bbnavi
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      bbnavi-redis-server: {}
      default: {}
      public: {}
    volumes:
    - assets:/assets:rw
    - unicorn:/unicorn:rw
  db:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: smart
      MYSQL_PASSWORD: smart
      MYSQL_ROOT_PASSWORD: smart
      MYSQL_USER: smart
    image: mysql:5.7.21
    networks:
      adminer:
        aliases:
        - int-development-mainserver
      default: {}
    volumes:
    - db:/var/lib/mysql:rw
  delayed_job:
    command: bin/delayed_job run
    configs:
    - source: bbnavi-datahub-credentials
      target: /app/releases/bbnavi/credentials.yml
    - source: mainserver-common-master-key
      target: /app/config/master.key
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      SVA_COMMUNITY: bbnavi
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      bbnavi-redis-server: {}
      default: {}
    volumes:
    - assets:/assets:rw
    - unicorn:/unicorn:rw
  nginx:
    configs:
    - source: smart-village-app-mainserver-nginx-conf
      target: /etc/nginx/conf.d/default.conf
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.rule: Host:datahub.bbnavi.de
        traefik.port: '80'
      restart_policy:
        condition: on-failure
    image: nginx
    labels:
      traefik.frontend.rule: Host:smartvillage.app
    networks:
      default: {}
      public: {}
    volumes:
    - assets:/public:rw
    - unicorn:/unicorn:rw
  redis:
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    image: docker.io/bitnami/redis:6.0-debian-10
    networks:
      bbnavi-redis-server:
        aliases:
        - bbnavi-redis-server
    volumes:
    - redis_data:/bitnami/redis/data:rw
version: '3.7'
volumes:
  assets: {}
  db:
    external: true
    name: db
  redis_data:
    external: true
    name: redis_data
  unicorn: {}

