configs:
  smart-village-app-mainserver-database-yml:
    external: true
    name: smart-village-app-mainserver-database-yml
  smart-village-app-mainserver-nginx-conf:
    external: true
    name: smart-village-app-mainserver-nginx-conf
  smart-village-app-mainserver-unicorn-rb:
    external: true
    name: smart-village-app-mainserver-unicorn-rb
networks:
  adminer:
    external: true
    name: adminer
  public:
    external: true
    name: public
  sva-redis-server:
    external: true
    name: sva-redis-server
services:
  app:
    configs:
    - source: smart-village-app-mainserver-database-yml
      target: /app/config/database.yml
    - source: smart-village-app-mainserver-unicorn-rb
      target: /app/config/unicorn.rb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      default: {}
      sva-redis-server: {}
    volumes:
    - assets:/assets:rw
    - /etc/localtime:/etc/localtime:ro
    - unicorn:/unicorn:rw
  cron_job:
    command: bin/start-cron.sh
    configs:
    - source: smart-village-app-mainserver-database-yml
      target: /app/config/database.yml
    - source: smart-village-app-mainserver-unicorn-rb
      target: /app/config/unicorn.rb
    deploy:
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.schedule: 1 1 1 * * *
        swarm.cronjob.skip-running: "true"
        traefik.docker.network: public
      replicas: 0
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      default: {}
      public: {}
      sva-redis-server: {}
    volumes:
    - assets:/assets:rw
    - /etc/localtime:/etc/localtime:ro
    - unicorn:/unicorn:rw
  db:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: smart
      MYSQL_PASSWORD: smart
      MYSQL_ROOT_PASSWORD: smart
      MYSQL_USER: smart
    image: mysql:5.7.21
    networks:
      adminer:
        aliases:
        - int-development-mainserver
      default: {}
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - db:/var/lib/mysql:rw
  delayed_job:
    command: bin/delayed_job start
    configs:
    - source: smart-village-app-mainserver-database-yml
      target: /app/config/database.yml
    - source: smart-village-app-mainserver-unicorn-rb
      target: /app/config/unicorn.rb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      default: {}
      sva-redis-server: {}
    volumes:
    - assets:/assets:rw
    - /etc/localtime:/etc/localtime:ro
    - unicorn:/unicorn:rw
  nginx:
    configs:
    - source: smart-village-app-mainserver-nginx-conf
      target: /etc/nginx/conf.d/default.conf
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.rule: Host:datahub.bb-navi.de
        traefik.port: '80'
      restart_policy:
        condition: on-failure
    image: nginx
    labels:
      traefik.frontend.rule: Host:smartvillage.app
    networks:
      default: {}
      public: {}
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - assets:/public:rw
    - unicorn:/unicorn:rw
version: '3.7'
volumes:
  assets: {}
  db: {}
  unicorn: {}

