version: '3.7'

services:
  tile_server:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:tileserver
    ports:
      - 5000:5000
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.port: 5000
        traefik.docker.network: public
        traefik.frontend.rule: Host:tiles.bbnavi.de

  delayed_job:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      - default
      - bbnavi-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1

  cron_job:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      - default
      - public
      - bbnavi-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 0
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.skip-running: "true"
        swarm.cronjob.schedule: 1 1 1 * * *
        traefik.docker.network: public
      restart_policy:
        condition: on-failure

  app:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      - default
      - bbnavi-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1

  nginx:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.docker.network: public
        traefik.frontend.rule: Host:datahub.bbnavi.de

  db:
    networks:
      default:
      adminer:
        aliases:
          - int-development-mainserver

  ssh-server:
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.redirect.entryPoint: https
        traefik.frontend.rule: Host:ssh.datahub.bbnavi.de
        traefik.port: '80'
      replicas: 0
      restart_policy:
        condition: on-failure
    environment:
      DOCKER_MODS: linuxserver/mods:openssh-server-ssh-tunnel
      PGID: '0'
      PUBLIC_KEY_DIR: /public_keys
      PUID: '0'
      SUDO_ACCESS: "true"
      TZ: Europe/Berlin
      USER_NAME: bbnavi
    expose:
    - '5432'
    image: ghcr.io/linuxserver/openssh-server
    networks:
      public: {}
      bbnavi-datahub-postgresql: {}
    volumes:
      - ssh_public_keys:/public_keys:rw
    ports:
    - published: 2222
      target: 2222

networks:
  adminer:
    external: true
  public:
    external: true
  ssh_public_keys:
    external: true
    name: ssh_public_keys
