version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      - default
      - bbnavi-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1

  cron_job:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      - default
      - public
      - bbnavi-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 0
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.skip-running: "true"
        swarm.cronjob.schedule: 1 1 1 * * *
        traefik.docker.network: public
      restart_policy:
        condition: on-failure

  app:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
    networks:
      - default
      - bbnavi-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1

  nginx:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.docker.network: public
        traefik.frontend.rule: Host:datahub.bb-navi.de

  db:
    networks:
      default:
      adminer:
        aliases:
          - int-development-mainserver

networks:
  adminer:
    external: true
  public:
    external: true
