name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:
  prep-martin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: registry.gitlab.tpwd.de
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    - id: docker_build
      uses: docker/build-push-action@v2
      with:
        cache-from: |
          type=registry,ref=registry.gitlab.tpwd.de/tpwd/bb-navi/datahub
        push: true
        file: Dockerfile.martin
        tags: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:tileserver
  prep:
    runs-on: ubuntu-latest
    needs:
      - prep-martin
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: registry.gitlab.tpwd.de
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    - id: docker_build
      uses: docker/build-push-action@v2
      with:
        cache-from: |
          type=registry,ref=registry.gitlab.tpwd.de/tpwd/bb-navi/datahub
        push: true
        tags: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:staging
  deploy:
    runs-on: ubuntu-latest
    needs:
      - prep
    container: r.planetary-quantum.com/quantum-public/cli:2
    env:
      QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
      QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
      QUANTUM_ENDPOINT: "tpwd-bb-navi"
      QUANTUM_STACK: "bbnavi-datahub-staging"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Planetary Quantum
        run: quantum-cli stacks update --create --wait
