name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Build the Docker image
        uses: actions/checkout@v2      
        run: docker build . --file Dockerfile --tag bbnavi-datahub:$(date +%s)

      -
        name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
