name: Docker Image CI

env:
  DOCKER_IMAGE: ghcr.io/bbnavi/datahub
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]

jobs:
  build-datahub-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/bbnavi/datahub:develop
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - prep
  #   container: r.planetary-quantum.com/quantum-public/cli:2
  #   env:
  #     QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
  #     QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
  #     QUANTUM_ENDPOINT: "tpwd-bb-navi"
  #     QUANTUM_STACK: "bbnavi-datahub"
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy to Planetary Quantum
  #       run: quantum-cli stacks update --create --wait
