name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkoput
        uses: actions/checkout@v2      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
      -
        name: Build the Docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:latest
